# Generated by Django 5.0.6 on 2024-07-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "agency_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("agency_name", models.CharField(max_length=100)),
                ("agency_url", models.URLField()),
                (
                    "agency_timezone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("agency_lang", models.CharField(blank=True, max_length=10, null=True)),
                ("agency_phone", models.CharField(max_length=20)),
            ],
        ),
    ]
