# Generated by Django 5.0.7 on 2024-07-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "service_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("monday", models.IntegerField()),
                ("tuesday", models.IntegerField()),
                ("wednesday", models.IntegerField()),
                ("thursday", models.IntegerField()),
                ("friday", models.IntegerField()),
                ("saturday", models.IntegerField()),
                ("sunday", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "db_table": "calendar",
            },
        ),
        migrations.CreateModel(
            name="CalendarAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_id", models.CharField(max_length=100)),
                ("service_description", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "calendar_attributes",
            },
        ),
        migrations.CreateModel(
            name="CalendarDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_id", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("exception_type", models.IntegerField()),
            ],
            options={
                "db_table": "calendar_dates",
            },
        ),
        migrations.CreateModel(
            name="Direction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_id", models.CharField(max_length=100)),
                ("direction_id", models.CharField(max_length=50)),
                ("direction", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "directions",
            },
        ),
        migrations.CreateModel(
            name="FareAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fare_id", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency_type", models.CharField(max_length=3)),
                ("payment_method", models.IntegerField()),
                ("transfers", models.IntegerField()),
                ("transfer_duration", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "fare_attributes",
            },
        ),
        migrations.CreateModel(
            name="FareRiderCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fare_id", models.CharField(max_length=100)),
                ("rider_category_id", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "fare_rider_categories",
            },
        ),
        migrations.CreateModel(
            name="FareRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fare_id", models.CharField(max_length=100)),
                ("route_id", models.CharField(blank=True, max_length=100, null=True)),
                ("origin_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "destination_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contains_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "fare_rules",
            },
        ),
        migrations.CreateModel(
            name="FeedInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_publisher_name", models.CharField(max_length=100)),
                ("feed_publisher_url", models.URLField()),
                ("feed_lang", models.CharField(max_length=10)),
                ("feed_start_date", models.DateField()),
                ("feed_end_date", models.DateField()),
                ("feed_version", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "feed_info",
            },
        ),
        migrations.CreateModel(
            name="RealtimeRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_id", models.CharField(max_length=100)),
                ("realtime_enabled", models.BooleanField()),
                (
                    "realtime_routename",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "realtime_routecode",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "realtime_routes",
            },
        ),
        migrations.CreateModel(
            name="RiderCategory",
            fields=[
                (
                    "rider_category_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("rider_category_description", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "rider_categories",
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "route_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "route_short_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("route_long_name", models.CharField(max_length=255)),
                ("route_desc", models.CharField(blank=True, max_length=255, null=True)),
                ("route_type", models.IntegerField()),
                ("route_url", models.URLField(blank=True, null=True)),
                ("route_color", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "route_text_color",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "routes",
            },
        ),
        migrations.CreateModel(
            name="RouteAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_id", models.CharField(max_length=100)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("subcategory", models.CharField(blank=True, max_length=50, null=True)),
                ("running_way", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "route_attributes",
            },
        ),
        migrations.CreateModel(
            name="Shape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shape_id", models.CharField(max_length=100)),
                ("shape_pt_lat", models.FloatField()),
                ("shape_pt_lon", models.FloatField()),
                ("shape_pt_sequence", models.IntegerField()),
                ("shape_dist_traveled", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "shapes",
            },
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "stop_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("stop_code", models.CharField(blank=True, max_length=50, null=True)),
                ("stop_name", models.CharField(max_length=255)),
                ("stop_desc", models.CharField(blank=True, max_length=255, null=True)),
                ("stop_lat", models.FloatField()),
                ("stop_lon", models.FloatField()),
                ("zone_id", models.CharField(blank=True, max_length=50, null=True)),
                ("plc_url", models.URLField(blank=True, null=True)),
                ("location_type", models.IntegerField(blank=True, null=True)),
                (
                    "parent_station",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "stops",
            },
        ),
        migrations.CreateModel(
            name="StopTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_id", models.CharField(max_length=100)),
                ("arrival_time", models.CharField(max_length=20)),
                ("departure_time", models.CharField(max_length=20)),
                ("stop_id", models.CharField(max_length=100)),
                ("stop_sequence", models.IntegerField()),
                (
                    "stop_headsign",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pickup_type", models.IntegerField(blank=True, null=True)),
                ("drop_off_type", models.IntegerField(blank=True, null=True)),
                ("shape_distance_traveled", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "stop_times",
            },
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_stop_id", models.CharField(max_length=100)),
                ("to_stop_id", models.CharField(max_length=100)),
                ("transfer_type", models.IntegerField()),
                ("min_transfer_time", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "transfers",
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                ("route_id", models.CharField(max_length=100)),
                ("service_id", models.CharField(max_length=100)),
                (
                    "trip_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "trip_headsign",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "direction_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("block_id", models.CharField(blank=True, max_length=50, null=True)),
                ("shape_id", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "trips",
            },
        ),
        migrations.AlterModelTable(
            name="agency",
            table="agency",
        ),
    ]
