# Generated by Django 5.0.7 on 2024-07-24 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bartapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="calendardate",
            unique_together={("service_id", "exception_type", "date")},
        ),
    ]
