# Generated by Django 5.0.7 on 2024-07-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartapp", "0002_alter_calendarattribute_service_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stoptime",
            name="stop_headsign",
            field=models.TextField(null=True),
        ),
    ]
