# Generated by Django 5.0.7 on 2024-07-31 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartapp", "0002_alter_calendardate_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realtimetrip",
            name="trip_id",
            field=models.OneToOneField(
                db_column="trip_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="bartapp.trip",
            ),
        ),
    ]
