# Generated by Django 5.0.7 on 2024-08-02 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartapp", "0003_alter_realtimetrip_trip_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="route_id",
            field=models.ForeignKey(
                db_column="route_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="bartapp.route",
            ),
        ),
    ]
