# Generated by Django 5.0.7 on 2024-07-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartapp", "0003_stoptime_stop_headsign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="route_desc",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="route",
            name="route_long_name",
            field=models.TextField(),
        ),
    ]
