# Generated by Django 5.0.7 on 2024-07-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartapp", "0004_alter_route_route_desc_alter_route_route_long_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="block_id",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="route_id",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="trip",
            name="service_id",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="trip",
            name="shape_id",
            field=models.TextField(null=True),
        ),
    ]
