# Generated by Django 5.0.7 on 2024-07-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartapp", "0005_alter_trip_block_id_alter_trip_route_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shape",
            name="shape_id",
            field=models.TextField(),
        ),
    ]
