# Generated by Django 5.0.7 on 2024-07-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bartapp", "0006_alter_shape_shape_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarattribute",
            name="service_description",
            field=models.TextField(),
        ),
    ]
