export const stationList = [
    {
      "name": "12th St. Oakland City Center",
      "abbr": "12TH",
      "lat": "37.803768",
      "lng": "-122.271450",
      "address": "1245 Broadway",
      "city": "Oakland",
      "county": "alameda",
      "state": "CA",
      "zipcode": "94612"
    },
    {
      "name": "16th St. Mission",
      "abbr": "16TH",
      "lat": "37.765062",
      "lng": "-122.419694",
      "address": "2000 Mission Street",
      "city": "San Francisco",
      "county": "sanfrancisco",
      "state": "CA",
      "zipcode": "94110"
    },
    {
      "name": "19th St. Oakland",
      "abbr": "19TH",
      "lat": "37.808350",
      "lng": "-122.268602",
      "address": "1900 Broadway",
      "city": "Oakland",
      "county": "alameda",
      "state": "CA",
      "zipcode": "94612"
    },
    {
      "name": "24th St. Mission",
      "abbr": "24TH",
      "lat": "37.752470",
      "lng": "-122.418143",
      "address": "2800 Mission Street",
      "city": "San Francisco",
      "county": "sanfrancisco",
      "state": "CA",
      "zipcode": "94110"
    },
    {
      "name": "Antioch",
      "abbr": "ANTC",
      "lat": "37.995388",
      "lng": "-121.780420",
      "address": "1600 Slatten Ranch Road",
      "city": "Antioch",
      "county": "Contra Costa",
      "state": "CA",
      "zipcode": "94509"
    },
    {
      "name": "Ashby",
      "abbr": "ASHB",
      "lat": "37.852803",
      "lng": "-122.270062",
      "address": "3100 Adeline Street",
      "city": "Berkeley",
      "county": "alameda",
      "state": "CA",
      "zipcode": "94703"
    },
    {
      "name": "Balboa Park",
      "abbr": "BALB",
      "lat": "37.721585",
      "lng": "-122.447506",
      "address": "401 Geneva Avenue",
      "city": "San Francisco",
      "county": "sanfrancisco",
      "state": "CA",
      "zipcode": "94112"
    },
    {
      "name": "Bay Fair",
      "abbr": "BAYF",
      "lat": "37.696924",
      "lng": "-122.126514",
      "address": "15242 Hesperian Blvd.",
      "city": "San Leandro",
      "county": "alameda",
      "state": "CA",
      "zipcode": "94578"
    },
    {
      "name": "Berryessa/North San Jose",
      "abbr": "BERY",
      "lat": "37.368473",
      "lng": "-121.874681",
      "address": "1620 Berryessa Road",
      "city": "San Jose",
      "county": "Santa Clara",
      "state": "CA",
      "zipcode": "95133"
    },
    {
      "name": "Castro Valley",
      "abbr": "CAST",
      "lat": "37.690746",
      "lng": "-122.075602",
      "address": "3301 Norbridge Dr.",
      "city": "Castro Valley",
      "county": "alameda",
      "state": "CA",
      "zipcode": "94546"
    },
    {
      "name": "Civic Center/UN Plaza",
      "abbr": "CIVC",
      "lat": "37.779732",
      "lng": "-122.414123",
      "address": "1150 Market Street",
      "city": "San Francisco",
      "county": "sanfrancisco",
      "state": "CA",
      "zipcode": "94102"
    },
    {
      "name": "Coliseum",
      "abbr": "COLS",
      "lat": "37.753661",
      "lng": "-122.196869",
      "address": "7200 San Leandro St.",
      "city": "Oakland",
      "county": "alameda",
      "state": "CA",
      "zipcode": "94621"
    },
    {
      "name": "Colma",
      "abbr": "COLM",
      "lat": "37.684638",
      "lng": "-122.466233",
      "address": "365 D Street",
      "city": "Colma",
      "county": "sanmateo",
      "state": "CA",
      "zipcode": "94014"
    },
    {
      "name": "Concord",
      "abbr": "CONC",
      "lat": "37.973737",
      "lng": "-122.029095",
      "address": "1451 Oakland Avenue",
      "city": "Concord",
      "county": "contracosta",
      "state": "CA",
      "zipcode": "94520"
    },
    {
      "name": "Daly City",
      "abbr": "DALY",
      "lat": "37.706121",
      "lng": "-122.469081",
      "address": "500 John Daly Blvd.",
      "city": "Daly City",
      "county": "sanmateo",
      "state": "CA",
      "zipcode": "94014"
    },
    {
      "name": "Downtown Berkeley",
      "abbr": "DBRK",
      "lat": "37.870104",
      "lng": "-122.268133",
      "address": "2160 Shattuck Avenue",
      "city": "Berkeley",
      "county": "alameda",
      "state": "CA",
      "zipcode": "94704"
    },
    {
      "name": "Dublin/Pleasanton",
      "abbr": "DUBL",
      "lat": "37.701687",
      "lng": "-121.899179",
      "address": "5801 Owens Dr.",
      "city": "Pleasanton",
      "county": "alameda",
      "state": "CA",
      "zipcode": "94588"
    },
    {
      "name": "El Cerrito del Norte",
      "abbr": "DELN",
      "lat": "37.925086",
      "lng": "-122.316794",
      "address": "6400 Cutting Blvd.",
      "city": "El Cerrito",
      "county": "contracosta",
      "state": "CA",
      "zipcode": "94530"
    },
    {
      "name": "El Cerrito Plaza",
      "abbr": "PLZA",
      "lat": "37.902632",
      "lng": "-122.298904",
      "address": "6699 Fairmount Avenue",
      "city": "El Cerrito",
      "county": "contracosta",
      "state": "CA",
      "zipcode": "94530"
    },
    {
      "name": "Embarcadero",
      "abbr": "EMBR",
      "lat": "37.792874",
      "lng": "-122.397020",
      "address": "298 Market Street",
      "city": "San Francisco",
      "county": "sanfrancisco",
      "state": "CA",
      "zipcode": "94111"
    },
    {
      "name": "Fremont",
      "abbr": "FRMT",
      "lat": "37.557465",
      "lng": "-121.976608",
      "address": "2000 BART Way",
      "city": "Fremont",
      "county": "alameda",
      "state": "CA",
      "zipcode": "94536"
    },
    {
      "name": "Fruitvale",
      "abbr": "FTVL",
      "lat": "37.774836",
      "lng": "-122.224175",
      "address": "3401 East 12th Street",
      "city": "Oakland",
      "county": "alameda",
      "state": "CA",
      "zipcode": "94601"
    },
    {
      "name": "Glen Park",
      "abbr": "GLEN",
      "lat": "37.733064",
      "lng": "-122.433817",
      "address": "2901 Diamond Street",
      "city": "San Francisco",
      "county": "sanfrancisco",
      "state": "CA",
      "zipcode": "94131"
    },
    {
      "name": "Hayward",
      "abbr": "HAYW",
      "lat": "37.669723",
      "lng": "-122.087018",
      "address": "699 'B' Street",
      "city": "Hayward",
      "county": "alameda",
      "state": "CA",
      "zipcode": "94541"
    },
    {
      "name": "Lafayette",
      "abbr": "LAFY",
      "lat": "37.893176",
      "lng": "-122.124630",
      "address": "3601 Deer Hill Road",
      "city": "Lafayette",
      "county": "contracosta",
      "state": "CA",
      "zipcode": "94549"
    },
    {
      "name": "Lake Merritt",
      "abbr": "LAKE",
      "lat": "37.797027",
      "lng": "-122.265180",
      "address": "800 Madison Street",
      "city": "Oakland",
      "county": "alameda",
      "state": "CA",
      "zipcode": "94607"
    },
    {
      "name": "MacArthur",
      "abbr": "MCAR",
      "lat": "37.829065",
      "lng": "-122.267040",
      "address": "555 40th Street",
      "city": "Oakland",
      "county": "alameda",
      "state": "CA",
      "zipcode": "94609"
    },
    {
      "name": "Millbrae",
      "abbr": "MLBR",
      "lat": "37.600271",
      "lng": "-122.386702",
      "address": "200 North Rollins Road",
      "city": "Millbrae",
      "county": "sanmateo",
      "state": "CA",
      "zipcode": "94030"
    },
    {
      "name": "Milpitas",
      "abbr": "MLPT",
      "lat": "37.410277",
      "lng": "-121.891081",
      "address": "1755 S. Milpitas Blvd.",
      "city": "Milpitas",
      "county": "Santa Clara",
      "state": "CA",
      "zipcode": "95035"
    },
    {
      "name": "Montgomery St.",
      "abbr": "MONT",
      "lat": "37.789405",
      "lng": "-122.401066",
      "address": "598 Market Street",
      "city": "San Francisco",
      "county": "sanfrancisco",
      "state": "CA",
      "zipcode": "94104"
    },
    {
      "name": "North Berkeley",
      "abbr": "NBRK",
      "lat": "37.873967",
      "lng": "-122.283440",
      "address": "1750 Sacramento Street",
      "city": "Berkeley",
      "county": "alameda",
      "state": "CA",
      "zipcode": "94702"
    },
    {
      "name": "North Concord/Martinez",
      "abbr": "NCON",
      "lat": "38.003193",
      "lng": "-122.024653",
      "address": "3700 Port Chicago Highway",
      "city": "Concord",
      "county": "contracosta",
      "state": "CA",
      "zipcode": "94520"
    },
    {
      "name": "Oakland International Airport",
      "abbr": "OAKL",
      "lat": "37.713238",
      "lng": "-122.212191",
      "address": "4 Airport Drive",
      "city": "Oakland",
      "county": "alameda",
      "state": "CA",
      "zipcode": "94621"
    },
    {
      "name": "Orinda",
      "abbr": "ORIN",
      "lat": "37.878361",
      "lng": "-122.183791",
      "address": "11 Camino Pablo",
      "city": "Orinda",
      "county": "contracosta",
      "state": "CA",
      "zipcode": "94563"
    },
    {
      "name": "Pittsburg/Bay Point",
      "abbr": "PITT",
      "lat": "38.018914",
      "lng": "-121.945154",
      "address": "1700 West Leland Road",
      "city": "Pittsburg",
      "county": "contracosta",
      "state": "CA",
      "zipcode": "94565"
    },
    {
      "name": "Pittsburg Center",
      "abbr": "PCTR",
      "lat": "38.016941",
      "lng": "-121.889457",
      "address": "2099 Railroad Avenue",
      "city": "Pittsburg",
      "county": "Contra Costa",
      "state": "CA",
      "zipcode": "94565"
    },
    {
      "name": "Pleasant Hill/Contra Costa Centre",
      "abbr": "PHIL",
      "lat": "37.928468",
      "lng": "-122.056012",
      "address": "1365 Treat Blvd.",
      "city": "Walnut Creek",
      "county": "contracosta",
      "state": "CA",
      "zipcode": "94597"
    },
    {
      "name": "Powell St.",
      "abbr": "POWL",
      "lat": "37.784471",
      "lng": "-122.407974",
      "address": "899 Market Street",
      "city": "San Francisco",
      "county": "sanfrancisco",
      "state": "CA",
      "zipcode": "94102"
    },
    {
      "name": "Richmond",
      "abbr": "RICH",
      "lat": "37.936853",
      "lng": "-122.353099",
      "address": "1700 Nevin Avenue",
      "city": "Richmond",
      "county": "contracosta",
      "state": "CA",
      "zipcode": "94801"
    },
    {
      "name": "Rockridge",
      "abbr": "ROCK",
      "lat": "37.844702",
      "lng": "-122.251371",
      "address": "5660 College Avenue",
      "city": "Oakland",
      "county": "alameda",
      "state": "CA",
      "zipcode": "94618"
    },
    {
      "name": "San Bruno",
      "abbr": "SBRN",
      "lat": "37.637761",
      "lng": "-122.416287",
      "address": "1151 Huntington Avenue",
      "city": "San Bruno",
      "county": "sanmateo",
      "state": "CA",
      "zipcode": "94066"
    },
    {
      "name": "San Francisco International Airport",
      "abbr": "SFIA",
      "lat": "37.615966",
      "lng": "-122.392409",
      "address": "International Terminal, Level 3",
      "city": "San Francisco Int'l Airport",
      "county": "sanmateo",
      "state": "CA",
      "zipcode": "94128"
    },
    {
      "name": "San Leandro",
      "abbr": "SANL",
      "lat": "37.721947",
      "lng": "-122.160844",
      "address": "1401 San Leandro Blvd.",
      "city": "San Leandro",
      "county": "alameda",
      "state": "CA",
      "zipcode": "94577"
    },
    {
      "name": "South Hayward",
      "abbr": "SHAY",
      "lat": "37.634375",
      "lng": "-122.057189",
      "address": "28601 Dixon Street",
      "city": "Hayward",
      "county": "alameda",
      "state": "CA",
      "zipcode": "94544"
    },
    {
      "name": "South San Francisco",
      "abbr": "SSAN",
      "lat": "37.664245",
      "lng": "-122.443960",
      "address": "1333 Mission Road",
      "city": "South San Francisco",
      "county": "sanmateo",
      "state": "CA",
      "zipcode": "94080"
    },
    {
      "name": "Union City",
      "abbr": "UCTY",
      "lat": "37.590630",
      "lng": "-122.017388",
      "address": "10 Union Square",
      "city": "Union City",
      "county": "alameda",
      "state": "CA",
      "zipcode": "94587"
    },
    {
      "name": "Walnut Creek",
      "abbr": "WCRK",
      "lat": "37.905522",
      "lng": "-122.067527",
      "address": "200 Ygnacio Valley Road",
      "city": "Walnut Creek",
      "county": "contracosta",
      "state": "CA",
      "zipcode": "94596"
    },
    {
      "name": "Warm Springs/South Fremont",
      "abbr": "WARM",
      "lat": "37.502171",
      "lng": "-121.939313",
      "address": "45193 Warm Springs Blvd",
      "city": "Fremont",
      "county": "alameda",
      "state": "CA",
      "zipcode": "94539"
    },
    {
      "name": "West Dublin/Pleasanton",
      "abbr": "WDUB",
      "lat": "37.699756",
      "lng": "-121.928240",
      "address": "6501 Golden Gate Drive",
      "city": "Dublin",
      "county": "alameda",
      "state": "CA",
      "zipcode": "94568"
    },
    {
      "name": "West Oakland",
      "abbr": "WOAK",
      "lat": "37.804872",
      "lng": "-122.295140",
      "address": "1451 7th Street",
      "city": "Oakland",
      "county": "alameda",
      "state": "CA",
      "zipcode": "94607"
    }
]

export const findStation = (abbreviation: string) => {
  if (abbreviation === "initial") return
  const {0: station} = stationList.filter((station) => station.abbr === abbreviation)
  return station
}